baseURL = "https://cours.usson.me/"
languageCode = "fr-fr"
title = "Intégration continue pour le web"
theme = "kiss"
copyright = '&copy; <a href="https://julien.usson.me/">Julien Usson</a> - Année 2022/2023 - ZZ2 F5'
poweredby = false
googleAnalytics="UA-148716459-1"
pygmentsUseClasses = true
pygmentsCodeFences = false # Reveal Hugo bugfix

[params]
# form = "https://docs.google.com/forms/d/e/1FAIpQLScx8qM4cEUco_rbbq9m4-etHBjuK2bVyANc5oaSkunoB2MGnw/viewform"

[params.assets]
customCSS = ["css/custom.css", "css/syntax.css"]

[params.social.config]
platforms = ["github","email","twitter","linkedin"]

[params.Info]
homeTitle="Intégration continue pour le web"

[params.social]
github = "JulienUsson"
email = "julien@usson.me"
twitter = "JulienUsson"
linkedin = "julien-usson-64bbbb107"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "simple"
highlight_theme = "vs2015"
slide_number=true

[markup.goldmark.renderer]
unsafe= true
