baseURL = "https://cours.usson.me/"
languageCode = "fr-fr"
title = "Intégration continue pour le web"
theme = "kiss"
copyright = "&copy; Julien Usson"
poweredby = false
googleAnalytics="UA-148716459-1"
pygmentsUseClasses = true
pygmentsCodeFences = false # Reaveal Hugo bugfix

[params.assets]
customCSS = ["css/custom.css", "css/syntax.css"]

[params.social.config]
platforms = ["github","email","twitter","linkedin"]

[params.social]
github = "JulienUsson"
email = "julien@usson.me"
twitter = "JulienUsson"
linkedin = "julien-usson-64bbbb107"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "simple"
highlight_theme = "monokai"
slide_number=true
